### ISSUE TITLE
No Longer Works With Asuracomic.net

### ISSUE THREAD

**Issue by killer93551277** [Astropilot/webtoon_userscripts#1]
Title.

I've tried adding "asuracomic.net" to line 33, so it looks like "hosts: ["asuratoon.com", "asuracomic.net", "xcalibrscans.com"]," but that didn't work

**Comment by Astropilot** [comment]
Hi there,
Indeed just adding the new domain name will not work in this specific case because they also changed their whole website so the selectors will also need to be updated.
I will make the update, as soon as the website is up again (bad timing it is currently down).

Kind regards,
Astropilot

**Comment by Astropilot** [comment]
I updated the script and it is now working properly with the new asuracomic website!

**Comment by killer93551277** [comment]
I've confirmed it's working, thanks for the update
